-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 09:42:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `recetas` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recetas` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `recetas` ;

-- -----------------------------------------------------
-- Table `tipo_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_usuarios` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `fk_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `mail_UNIQUE` ON `usuarios` (`mail` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categorias` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categorias`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recetas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `recetas` (
  `id_recetas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `descripcion` TINYTEXT NOT NULL,
  `ingredientes` VARCHAR(45) NOT NULL,
  `pasos` VARCHAR(45) NOT NULL,
  `fk_usuarios` INT NOT NULL,
  `fk_id_categorias` INT NOT NULL,
  PRIMARY KEY (`id_recetas`, `fk_id_categorias`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
